version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: 
        name: Install Mkdocs
          command: sudo pip install mkdocs
      - run:
        name: Deploy
          command: mkdocs gh-deploy

workflows:
  version: 2
  build_docs_deploy:
    jobs:
      - build

